import type { Database } from "@/src/types/database";

type LabTestInsert = Database["public"]["Tables"]["tests"]["Insert"];

type StarterTestDefinition = Omit<LabTestInsert, "id" | "created_at" | "org_id">;

export const STARTER_TEST_CATALOG: StarterTestDefinition[] = [
  {
    test_name: "Complete Blood Count (CBC)",
    category: "Hematology",
    price: 25,
    normal_range: "WBC 4,000-11,000/uL; Hb Adult M 13.5-17.5 g/dL, F 12.0-15.5 g/dL",
    reference_range: "WBC 4,000-11,000/uL; Platelets 150,000-450,000/uL",
    units: "Panel",
  },
  {
    test_name: "Erythrocyte Sedimentation Rate (ESR)",
    category: "Hematology",
    price: 10,
    normal_range: "0-20 mm/hr",
    reference_range: "Adult male 0-15 mm/hr; adult female 0-20 mm/hr",
    units: "mm/hr",
  },
  {
    test_name: "Hemoglobin (Hb)",
    category: "Hematology",
    price: 8,
    normal_range: "Adult male 13.5-17.5 g/dL; adult female 12.0-15.5 g/dL",
    reference_range: "Male 13.5-17.5 g/dL; Female 12.0-15.5 g/dL",
    units: "g/dL",
  },
  {
    test_name: "Blood Sugar (Fasting)",
    category: "Biochemistry",
    price: 12,
    normal_range: "70-99 mg/dL",
    reference_range: "Normal 70-99 mg/dL; impaired fasting 100-125 mg/dL",
    units: "mg/dL",
  },
  {
    test_name: "Blood Sugar (Postprandial)",
    category: "Biochemistry",
    price: 12,
    normal_range: "<140 mg/dL",
    reference_range: "Normal <140 mg/dL; impaired 140-199 mg/dL",
    units: "mg/dL",
  },
  {
    test_name: "HbA1c",
    category: "Biochemistry",
    price: 20,
    normal_range: "4.0-5.6%",
    reference_range: "Normal <5.7%; prediabetes 5.7-6.4%; diabetes >=6.5%",
    units: "%",
  },
  {
    test_name: "Lipid Profile",
    category: "Biochemistry",
    price: 35,
    normal_range: "Total cholesterol <200 mg/dL; Triglycerides <150 mg/dL",
    reference_range: "LDL <100 mg/dL; HDL >40 mg/dL",
    units: "Panel",
  },
  {
    test_name: "Liver Function Test (LFT)",
    category: "Biochemistry",
    price: 30,
    normal_range: "ALT 7-56 U/L; AST 10-40 U/L",
    reference_range: "Bilirubin total 0.3-1.2 mg/dL",
    units: "Panel",
  },
  {
    test_name: "Kidney Function Test (KFT)",
    category: "Biochemistry",
    price: 28,
    normal_range: "Creatinine 0.7-1.3 mg/dL; Urea 15-40 mg/dL",
    reference_range: "BUN 7-20 mg/dL",
    units: "Panel",
  },
  {
    test_name: "Serum Creatinine",
    category: "Biochemistry",
    price: 9,
    normal_range: "0.7-1.3 mg/dL",
    reference_range: "Adult 0.7-1.3 mg/dL",
    units: "mg/dL",
  },
  {
    test_name: "Blood Urea",
    category: "Biochemistry",
    price: 9,
    normal_range: "15-40 mg/dL",
    reference_range: "Adult 15-40 mg/dL",
    units: "mg/dL",
  },
  {
    test_name: "Electrolytes (Na/K/Cl)",
    category: "Biochemistry",
    price: 22,
    normal_range: "Na 135-145; K 3.5-5.0; Cl 98-106",
    reference_range: "Sodium 135-145 mEq/L; Potassium 3.5-5.0 mEq/L",
    units: "mEq/L",
  },
  {
    test_name: "Thyroid Stimulating Hormone (TSH)",
    category: "Endocrinology",
    price: 18,
    normal_range: "0.4-4.0 mIU/L",
    reference_range: "Adult 0.4-4.0 mIU/L",
    units: "mIU/L",
  },
  {
    test_name: "Triiodothyronine (T3)",
    category: "Endocrinology",
    price: 15,
    normal_range: "80-200 ng/dL",
    reference_range: "Adult 80-200 ng/dL",
    units: "ng/dL",
  },
  {
    test_name: "Thyroxine (T4)",
    category: "Endocrinology",
    price: 15,
    normal_range: "5.0-12.0 ug/dL",
    reference_range: "Adult 5.0-12.0 ug/dL",
    units: "ug/dL",
  },
  {
    test_name: "Vitamin D (25-OH)",
    category: "Vitamins",
    price: 28,
    normal_range: "30-100 ng/mL",
    reference_range: "Deficient <20 ng/mL; insufficient 20-29 ng/mL",
    units: "ng/mL",
  },
  {
    test_name: "Vitamin B12",
    category: "Vitamins",
    price: 24,
    normal_range: "200-900 pg/mL",
    reference_range: "Adult 200-900 pg/mL",
    units: "pg/mL",
  },
  {
    test_name: "C-Reactive Protein (CRP)",
    category: "Immunology",
    price: 14,
    normal_range: "<5 mg/L",
    reference_range: "Adult <5 mg/L",
    units: "mg/L",
  },
  {
    test_name: "D-Dimer",
    category: "Coagulation",
    price: 32,
    normal_range: "<500 ng/mL FEU",
    reference_range: "Adult <500 ng/mL FEU",
    units: "ng/mL FEU",
  },
  {
    test_name: "Urine Routine Examination",
    category: "Clinical Pathology",
    price: 10,
    normal_range: "pH 4.5-8.0; Protein negative; Glucose negative",
    reference_range: "Specific gravity 1.005-1.030",
    units: "Panel",
  },
];
